repos:
-   repo: local
    hooks:
    -   id: convert-readme
        name: Convert README.md to README.rst
        entry: pandoc --from=markdown --to=rst --output=README.rst README.md
        language: system
        files: README.md
        stages:
          - commit

-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest before push
        entry: poetry run pytest
        language: system
        stages: [pre-push]